name: namisic_local

networks:
  namisic_local_net:
    external: true

volumes:
  namisic_local_db:

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.7-ubuntu2204
    container_name: namisic_db_local
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eladmin
      - MONGO_INITDB_ROOT_PASSWORD=namisic_2025
    ports:
      - 27017:27017
    networks:
      - namisic_local_net
    restart: on-failure:3
    volumes:
      - namisic_local_db:/data/db
      - ./mongodb:/data/db/scripts

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namisic_api_local
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://*:80
      MongoDB__ConnectionString: mongodb://eladmin:namisic_2025@mongodb/
      MongoDB__DbName: namiSIC
    ports:
      - 5000:80
    networks:
      - namisic_local_net
    restart: on-failure:3
    volumes:
      - ./src:/app
