name: namisic_local

networks:
  namisic_local_net:
    external: true

volumes:
  namisic_local_db:

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0.7-ubuntu2204
    container_name: namisic_local_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eladmin
      - MONGO_INITDB_ROOT_PASSWORD=namisic_2025
    ports:
      - 27017:27017
    networks:
      - namisic_local_net
    volumes:
      - namisic_local_db:/data/db
      - ./mongodb:/data/db/scripts

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: namisic_local_api
    depends_on:
      - mongodb
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:80"
      MongoDB__ConnectionString: "mongodb://eladmin:namisic_2025@mongodb"
      MongoDB__DbName: "namisic"
      IdServerUrl: "https://auth.lechediaz.com/demo"
      ClientId: "namisic"
      RoleNames__Administrator: "namisic/representante_legal"
      RoleNames__SecurityGuard: "namisic/empleado_seguridad"
      GeneralSettings__CondominiumName: "Unidad Residencial Local"
      GeneralSettings__CondominiumDescription: "Aprendiendo a vivir en comunidad"
      GeneralSettings__CondominiumAddress: "localhost"
      GeneralSettings__CondominiumPhone: "0123456789"
      Files__ImagesPath: "/uploads/images/"
      Files__DocumentsPath: "/uploads/documents/"
      Files__MaxSize: "5"
      Files__StorageUri: "https://localhost:5000"
    ports:
      - 5000:80
    networks:
      - namisic_local_net
    volumes:
      - ./uploads:/uploads:rw
